name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt-openjdk'

      - name: Build and test
        run: ./gradlew build # mvn clean install

      - name: Increment version
        id: version
        run: |
          VERSION=$(./scripts/increment_version.sh)
          echo "VERSION=$VERSION" >> $GITHUB_ENV
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Generate changelog
        id: changelog
        run: |
          ./scripts/generate_changelog.sh
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Commit version and changelog
        run: |
          git config user.name "Jairo0516"
          git config user.email "jairoandres689@gmail.com"
          git add version.txt CHANGELOG.md
          git commit -m "chore: update version to $VERSION and update changelog"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Deploy
        run: |
          echo "Simulating deployment to production environment"
          # Comandos de despliegue
        env:
          VERSION: ${{ env.VERSION }}
